const tabs=[...document.querySelectorAll('[data-tab]')],loginForm=document.querySelector('#login-form'),registerForm=document.querySelector('#register-form');
const feedback=(id,message,type='error')=>{const box=document.querySelector(id);box.textContent=message;box.className=`auth-feedback ${type}`};
function showTab(name){tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===name));loginForm.classList.toggle('hidden',name!=='login');registerForm.classList.toggle('hidden',name!=='register')}
tabs.forEach(button=>button.addEventListener('click',()=>showTab(button.dataset.tab)));
const params=new URLSearchParams(location.search);if(params.get('cadastro')==='1')showTab('register');
window.sb.auth.getSession().then(({data})=>{if(data.session)location.replace(params.get('next')||'usuario.html')});
loginForm.addEventListener('submit',async event=>{event.preventDefault();const button=loginForm.querySelector('[type=submit]');button.disabled=true;feedback('#login-feedback','Entrando…','success');const data=Object.fromEntries(new FormData(loginForm));const {error}=await window.sb.auth.signInWithPassword({email:data.email,password:data.password});button.disabled=false;if(error)return feedback('#login-feedback',error.message==='Invalid login credentials'?'E-mail ou senha incorretos.':error.message);location.replace(params.get('next')||'usuario.html')});
registerForm.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(registerForm));if(data.password!==data.password_confirmation)return feedback('#register-feedback','As duas senhas precisam ser iguais.');const button=registerForm.querySelector('[type=submit]');button.disabled=true;feedback('#register-feedback','Criando sua conta…','success');const {data:result,error}=await window.sb.auth.signUp({email:data.email,password:data.password,options:{emailRedirectTo:new URL('usuario.html',location.href).href,data:{full_name:data.full_name,rg:data.rg,address:data.address,city:data.city,phone:data.phone,social:data.social||null,privacy_accepted:true}}});button.disabled=false;if(error)return feedback('#register-feedback',error.message);if(result.session)location.replace(params.get('next')||'usuario.html');else feedback('#register-feedback','Conta criada. Abra o e-mail de confirmação para ativar seu acesso.','success')});
document.querySelector('#forgot').addEventListener('click',async()=>{const email=loginForm.elements.email.value;if(!email)return feedback('#login-feedback','Informe seu e-mail primeiro.');const {error}=await window.sb.auth.resetPasswordForEmail(email,{redirectTo:new URL('login.html',location.href).href});feedback('#login-feedback',error?error.message:'Enviamos as instruções para o seu e-mail.',error?'error':'success')});
