const loginForm=document.querySelector('#login-form'),registerForm=document.querySelector('#register-form'),steps=[...document.querySelectorAll('.register-step')],progressLabels=[...document.querySelectorAll('[data-progress]')],nextButton=document.querySelector('#register-next'),backButton=document.querySelector('#register-back'),submitButton=document.querySelector('#register-submit'),progressBar=document.querySelector('#register-progress-bar');let currentStep=0;
const feedback=(id,message,type='error')=>{const box=document.querySelector(id);box.textContent=message;box.className=`auth-feedback ${type}`};
function showView(name){loginForm.classList.toggle('hidden',name!=='login');registerForm.classList.toggle('hidden',name!=='register');if(name==='register'){currentStep=0;updateStep();setTimeout(()=>registerForm.querySelector('input')?.focus(),250)}}
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();showView(button.dataset.tab)}));
const params=new URLSearchParams(location.search),patientRegistrationIntent=params.get('cadastro')==='1';
const publicSignupClient=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false,storageKey:'ea-public-patient-signup'}});
if(patientRegistrationIntent)showView('register');
else window.sb.auth.getSession().then(async({data})=>{if(data.session)location.replace(await window.acolherDestination(params.get('next')))}).catch(()=>feedback('#login-feedback','Não foi possível verificar o acesso. Tente novamente.'));

function updateStep(){steps.forEach((step,index)=>step.classList.toggle('active',index===currentStep));progressLabels.forEach((label,index)=>label.classList.toggle('active',index<=currentStep));progressBar.style.width=`${(currentStep+1)/steps.length*100}%`;backButton.classList.toggle('hidden',currentStep===0);nextButton.classList.toggle('hidden',currentStep===steps.length-1);submitButton.classList.toggle('hidden',currentStep!==steps.length-1);feedback('#register-feedback','');registerForm.scrollIntoView({behavior:'smooth',block:'start'})}
function validateStep(){const fields=[...steps[currentStep].querySelectorAll('[required]')];for(const field of fields){if(!field.checkValidity()){field.reportValidity();return false}}if(currentStep===0){const name=registerForm.elements.full_name.value.trim().replace(/\s+/g,' '),cpf=registerForm.elements.cpf.value.replace(/\D/g,''),phone=registerForm.elements.phone.value.replace(/\D/g,'');if(name.split(' ').length<2)return feedback('#register-feedback','Informe nome e sobrenome.'),false;if(!validCPF(cpf))return feedback('#register-feedback','Informe um CPF válido.'),false;if(!/^\d{10,11}$/.test(phone)||/^(\d)\1+$/.test(phone))return feedback('#register-feedback','Informe um celular válido, com DDD.'),false}if(currentStep===1&&registerForm.elements.cep.dataset.valid!=='true')return feedback('#register-feedback','Consulte um CEP válido antes de continuar.'),false;return true}
nextButton.addEventListener('click',()=>{if(!validateStep())return;currentStep++;updateStep()});backButton.addEventListener('click',()=>{if(currentStep>0){currentStep--;updateStep()}});

loginForm.addEventListener('submit',async event=>{
 event.preventDefault();const button=loginForm.querySelector('[type=submit]');if(button.disabled)return;
 const data=Object.fromEntries(new FormData(loginForm));button.disabled=true;feedback('#login-feedback','Entrando…','success');
 try {const {error}=await window.sb.auth.signInWithPassword({email:data.email.trim().toLowerCase(),password:data.password});
 if(error)throw error;location.replace(await window.acolherDestination(params.get('next')));
 }catch(error){feedback('#login-feedback',error.message==='Invalid login credentials'?'E-mail ou senha incorretos. Confirme também se sua conta já foi ativada.':error.message==='Email not confirmed'?'Confirme seu e-mail antes de entrar. Você pode reenviar a ativação abaixo.':'Não foi possível entrar. Confira sua conexão e tente novamente.');}
 finally{button.disabled=false;}
});
document.querySelector('#forgot').addEventListener('click',async event=>{const email=loginForm.elements.email.value.trim();if(!loginForm.elements.email.checkValidity()){loginForm.elements.email.reportValidity();return;}const button=event.currentTarget;if(button.disabled)return;button.disabled=true;try{const {error}=await window.sb.auth.resetPasswordForEmail(email,{redirectTo:new URL('recuperar-senha.html',location.href).href});if(error)throw error;feedback('#login-feedback','Solicitação aceita. Verifique seu e-mail e o spam.','success');}catch{feedback('#login-feedback','Não foi possível solicitar a recuperação. Tente novamente.');}finally{button.disabled=false;}});

registerForm.addEventListener('submit',async event=>{
 event.preventDefault();if(submitButton.disabled||!validateStep())return;
 const data=Object.fromEntries(new FormData(registerForm)),email=data.email.trim().toLowerCase();
 if(!/^[a-z0-9._-]{3,24}$/.test(data.username))return feedback('#register-feedback','Escolha um nome de usuário válido.');
 if(!strongPassword(data.password))return feedback('#register-feedback','A senha ainda não atende a todos os requisitos.');
 if(data.password!==data.password_confirmation)return feedback('#register-feedback','As duas senhas precisam ser iguais.');
 const address=`${data.street}, ${data.number}${data.complement?` - ${data.complement}`:''}, ${data.neighborhood}`;
 submitButton.disabled=true;feedback('#register-feedback','Criando sua conta segura…','success');
 try {
  const {data:result,error}=await publicSignupClient.auth.signUp({email,password:data.password,options:{emailRedirectTo:new URL('login.html?next=triagem.html',location.href).href,data:{full_name:data.full_name.trim(),username:data.username,rg:data.cpf,cep:data.cep,address,street:data.street,address_number:data.number,address_complement:data.complement||null,neighborhood:data.neighborhood,city:data.city,state:data.state,phone:data.phone,social:data.social||null,privacy_accepted:true}}});
  if(error)throw error;
  if(result.session){await publicSignupClient.auth.signOut({scope:'local'});return feedback('#register-feedback','O servidor não exigiu a confirmação do e-mail. A configuração de ativação precisa ser revisada antes de continuar.');}
  steps.forEach(step=>step.classList.remove('active'));
  document.querySelector('.register-progress').classList.add('hidden');document.querySelector('.register-actions').classList.add('hidden');registerForm.querySelector('.register-top').classList.add('hidden');
  registerForm.insertAdjacentHTML('afterbegin','<div class="activation-success"><span>✓</span><p>CADASTRO RECEBIDO — AGUARDANDO CONFIRMAÇÃO</p><h2>Confirme seu e-mail</h2><div>Verifique a caixa de entrada e o spam de <b>'+window.acolherSafety.escape(email)+'</b>. Se já existir uma conta, use entrar ou reenviar ativação. Após confirmar, informe para quem é o atendimento e um pouco da sua história na solicitação.</div><button class="portal-button" type="button" data-tab="login">Ir para entrar ou reenviar ativação</button></div>');
  registerForm.querySelector('[data-tab="login"]').addEventListener('click',()=>showView('login'));
 }catch(error){feedback('#register-feedback',String(error.message||'Não foi possível conectar. Tente novamente.').includes('profiles_username_key')?'Este nome de usuário já está em uso.':String(error.message||'Não foi possível conectar. Tente novamente.'));}
 finally{submitButton.disabled=false;}
});
document.querySelector('#resend-activation').addEventListener('click',async event=>{
 const email=loginForm.elements.email.value.trim().toLowerCase();
 if(!loginForm.elements.email.checkValidity()){loginForm.elements.email.reportValidity();return;}
 const button=event.currentTarget;button.disabled=true;
 try{const {error}=await publicSignupClient.auth.resend({type:'signup',email,options:{emailRedirectTo:new URL('login.html?next=triagem.html',location.href).href}});
 if(error)throw error;feedback('#login-feedback','Solicitação de reenvio aceita. Verifique a caixa de entrada e o spam; a conta precisa estar aguardando confirmação.','success');
 }catch{feedback('#login-feedback','Não foi possível reenviar a ativação. O serviço de e-mail pode estar indisponível ou limitado. Tente novamente mais tarde.');}
 finally{button.disabled=false;}
});
if(params.get('confirmacao')==='1')feedback('#login-feedback','Confirme seu e-mail antes de acessar. Informe o endereço e toque em Reenviar ativação.');
if(params.get('error')||location.hash.includes('error='))feedback('#login-feedback','O link de ativação expirou ou é inválido. Solicite outro pelo botão Reenviar ativação.');

const cepInput=registerForm.elements.cep,cepStatus=document.querySelector('#cep-status');cepInput.addEventListener('input',event=>{cepInput.dataset.valid='false';const digits=event.target.value.replace(/\D/g,'').slice(0,8);event.target.value=digits.length>5?`${digits.slice(0,5)}-${digits.slice(5)}`:digits});cepInput.addEventListener('blur',async()=>{const cep=cepInput.value.replace(/\D/g,'');if(cep.length!==8){cepStatus.textContent='Digite os 8 números do CEP.';return}cepStatus.textContent='Buscando endereço…';cepStatus.className='loading';try{const response=await fetch(`https://viacep.com.br/ws/${cep}/json/`),data=await response.json();if(!response.ok||data.erro)throw new Error();registerForm.elements.street.value=data.logradouro||'';registerForm.elements.neighborhood.value=data.bairro||'';registerForm.elements.city.value=data.localidade||'';registerForm.elements.state.value=data.uf||'SP';cepInput.dataset.valid='true';cepStatus.textContent='Endereço encontrado ✓';cepStatus.className='success';registerForm.elements.number.focus()}catch{cepInput.dataset.valid='false';cepStatus.textContent='CEP não encontrado. Confira e tente novamente.';cepStatus.className='error'}});
registerForm.elements.cpf.addEventListener('input',event=>{const digits=event.target.value.replace(/\D/g,'').slice(0,11);let value=digits;if(digits.length>3)value=`${digits.slice(0,3)}.${digits.slice(3)}`;if(digits.length>6)value=`${digits.slice(0,3)}.${digits.slice(3,6)}.${digits.slice(6)}`;if(digits.length>9)value=`${digits.slice(0,3)}.${digits.slice(3,6)}.${digits.slice(6,9)}-${digits.slice(9)}`;event.target.value=value});
registerForm.elements.phone.addEventListener('input',event=>{const digits=event.target.value.replace(/\D/g,'').slice(0,11);let value=digits;if(digits.length>2)value=`(${digits.slice(0,2)}) ${digits.slice(2)}`;if(digits.length>6)value=`(${digits.slice(0,2)}) ${digits.length===11?digits.slice(2,7):digits.slice(2,6)}-${digits.length===11?digits.slice(7):digits.slice(6)}`;event.target.value=value});
registerForm.elements.username.addEventListener('input',event=>event.target.value=event.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,''));
const passwordInput=registerForm.elements.password,passwordConfirm=registerForm.elements.password_confirmation,passwordRules=document.querySelector('#password-rules'),passwordStrength=document.querySelector('#password-strength');passwordInput.addEventListener('input',()=>{const value=passwordInput.value,rules={length:value.length>=8,upper:/[A-Z]/.test(value),lower:/[a-z]/.test(value),number:/\d/.test(value),symbol:/[^A-Za-z0-9]/.test(value)};Object.entries(rules).forEach(([rule,ok])=>passwordRules.querySelector(`[data-rule="${rule}"]`).classList.toggle('ok',ok));const score=Object.values(rules).filter(Boolean).length+(value.length>=12?1:0);let level='',message='Digite uma senha para avaliar a força.';if(value){if(score<=2){level='weak';message='Senha fraca — adicione mais tipos de caracteres.'}else if(score<=4){level='medium';message='Senha média — falta pouco para ficar forte.'}else{level='strong';message='Senha forte — todos os requisitos foram atendidos.'}}passwordStrength.className=`password-strength ${level}`;passwordStrength.querySelector('span').textContent=message});passwordConfirm.addEventListener('input',()=>passwordConfirm.setCustomValidity(passwordConfirm.value===passwordInput.value?'':'As senhas não coincidem'));
function strongPassword(value){return value.length>=8&&/[A-Z]/.test(value)&&/[a-z]/.test(value)&&/\d/.test(value)&&/[^A-Za-z0-9]/.test(value)}function validCPF(cpf){if(!/^\d{11}$/.test(cpf)||/^(\d)\1{10}$/.test(cpf))return false;for(let t=9;t<11;t++){let sum=0;for(let i=0;i<t;i++)sum+=Number(cpf[i])*(t+1-i);let digit=(sum*10)%11;if(digit===10)digit=0;if(digit!==Number(cpf[t]))return false}return true}

const authArt=document.querySelector('.auth-side');
if(authArt&&matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){authArt.addEventListener('pointermove',event=>{const box=authArt.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;authArt.style.setProperty('--mx',`${x*22}px`);authArt.style.setProperty('--my',`${y*18}px`)});authArt.addEventListener('pointerleave',()=>{authArt.style.setProperty('--mx','0px');authArt.style.setProperty('--my','0px')})}
