const loginForm=document.querySelector('#professional-login'),registerForm=document.querySelector('#professional-register');
const params=new URLSearchParams(location.search);
function feedback(id,message,type='error'){const el=document.querySelector(id);el.textContent=message;el.className=`feedback ${type}`}
function showView(view){loginForm.classList.toggle('hidden',view!=='login');registerForm.classList.toggle('hidden',view!=='register');document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));if(params.get('cadastro')==='1')showView('register');
loginForm.addEventListener('submit',async event=>{event.preventDefault();const button=loginForm.querySelector('button'),values=Object.fromEntries(new FormData(loginForm));button.disabled=true;feedback('#professional-login-feedback','Verificando sua conta…','success');const {data,error}=await window.sb.auth.signInWithPassword({email:values.email.trim().toLowerCase(),password:values.password});if(error){button.disabled=false;return feedback('#professional-login-feedback','E-mail ou senha incorretos. Confirme também se o e-mail já foi ativado.')}const {data:application}=await window.sb.from('professional_applications').select('id').eq('user_id',data.user.id).maybeSingle();if(!application){await window.sb.auth.signOut();button.disabled=false;return feedback('#professional-login-feedback','Esta conta não possui cadastro profissional. Use “Novo cadastro”.')}location.replace('profissional-area.html')});
registerForm.addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(registerForm));if(!strongPassword(values.password))return feedback('#professional-register-feedback','A senha ainda não atende a todos os requisitos.');if(values.password!==values.password_confirmation)return feedback('#professional-register-feedback','As senhas precisam ser iguais.');if(!/^\d{2}\/\d{4,6}$/.test(values.crp.trim()))return feedback('#professional-register-feedback','Informe o CRP no formato 06/000000.');const button=registerForm.querySelector('button[type=submit]');button.disabled=true;feedback('#professional-register-feedback','Enviando seu cadastro…','success');const email=values.email.trim().toLowerCase();const {data,error}=await window.sb.auth.signUp({email,password:values.password,options:{emailRedirectTo:new URL('profissional-area.html',location.href).href,data:{account_type:'profissional',full_name:values.full_name.trim(),crp:values.crp.trim(),phone:values.phone.trim(),city:values.city.trim(),specialties:values.specialties.trim(),presentation:values.presentation.trim(),privacy_accepted:true}}});button.disabled=false;if(error)return feedback('#professional-register-feedback',error.message);if(data.session)return location.replace('profissional-area.html');registerForm.innerHTML=`<div class="form-heading"><p>CADASTRO ENVIADO</p><h2>Confirme seu e-mail</h2><span>Enviamos um link de ativação para <b>${email}</b>. Depois da confirmação, você poderá acompanhar a análise do cadastro.</span></div><button type="button" class="professional-button" data-view="login">Ir para o acesso profissional →</button>`;registerForm.querySelector('[data-view]').addEventListener('click',()=>showView('login'))});
const password=registerForm.elements.password,meter=document.querySelector('#professional-password-meter');password.addEventListener('input',()=>{const value=password.value,score=[value.length>=8,/[A-Z]/.test(value),/[a-z]/.test(value),/\d/.test(value),/[^A-Za-z0-9]/.test(value)].filter(Boolean).length;meter.className=`password-meter ${score<=2?'weak':score<=4?'medium':'strong'}`;meter.querySelector('span').textContent=score<=2?'Senha fraca — acrescente diferentes caracteres.':score<=4?'Senha média — falta pouco para ficar forte.':'Senha forte — todos os requisitos foram atendidos.'});
registerForm.elements.phone.addEventListener('input',event=>{const digits=event.target.value.replace(/\D/g,'').slice(0,11);event.target.value=digits.length>6?`(${digits.slice(0,2)}) ${digits.length===11?digits.slice(2,7):digits.slice(2,6)}-${digits.length===11?digits.slice(7):digits.slice(6)}`:digits.length>2?`(${digits.slice(0,2)}) ${digits.slice(2)}`:digits});
function strongPassword(value){return value.length>=8&&/[A-Z]/.test(value)&&/[a-z]/.test(value)&&/\d/.test(value)&&/[^A-Za-z0-9]/.test(value)}
window.sb.auth.getSession().then(async({data})=>{if(!data.session)return;const {data:application}=await window.sb.from('professional_applications').select('id').eq('user_id',data.session.user.id).maybeSingle();if(application)location.replace('profissional-area.html')});
