const loginForm=document.querySelector('#professional-login'),registerForm=document.querySelector('#professional-register');
const params=new URLSearchParams(location.search);
function feedback(id,message,type='error'){const el=document.querySelector(id);el.textContent=message;el.className=`feedback ${type}`}
function showView(view){if(view==='register'&&registerForm.querySelector('.confirmation-state')){location.replace('profissional.html?cadastro=1');return;}loginForm.classList.toggle('hidden',view!=='login');registerForm.classList.toggle('hidden',view!=='register');document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));if(params.get('cadastro')==='1')showView('register');
loginForm.addEventListener('submit',async event=>{event.preventDefault();const button=loginForm.querySelector('[type=submit]'),values=Object.fromEntries(new FormData(loginForm));if(button.disabled)return;button.disabled=true;try{feedback('#professional-login-feedback','Verificando sua conta…','success');const {data,error}=await window.sb.auth.signInWithPassword({email:values.email.trim().toLowerCase(),password:values.password});if(!error&&!data.user.email_confirmed_at){await window.sb.auth.signOut({scope:'local'});throw Error('confirmation')}if(error){button.disabled=false;return feedback('#professional-login-feedback','E-mail ou senha incorretos. Confirme também se o e-mail já foi ativado.')}const {data:profile}=await window.sb.from('profiles').select('role').eq('id',data.user.id).maybeSingle();if(profile?.role==='admin')return location.replace('acolher-app/');const {data:application}=await window.sb.from('professional_applications').select('id').eq('user_id',data.user.id).maybeSingle();if(!application){await window.sb.auth.signOut();button.disabled=false;return feedback('#professional-login-feedback','Esta conta não possui cadastro profissional. Use “Novo cadastro”.')}location.replace('acolher-app/')}catch{feedback('#professional-login-feedback','Não foi possível conectar. Tente novamente.')}finally{button.disabled=false}});
registerForm.addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(registerForm));if(!strongPassword(values.password))return feedback('#professional-register-feedback','A senha ainda não atende a todos os requisitos.');if(values.password!==values.password_confirmation)return feedback('#professional-register-feedback','As senhas precisam ser iguais.');if(!/^\d{2}\/\d{4,6}$/.test(values.crp.trim()))return feedback('#professional-register-feedback','Informe o CRP no formato 06/000000.');const button=registerForm.querySelector('button[type=submit]');if(button.disabled)return;button.disabled=true;try{feedback('#professional-register-feedback','Enviando seu cadastro…','success');const email=values.email.trim().toLowerCase(),redirectTo=new URL('profissional-area.html?confirmado=1',location.href).href;const {data,error}=await window.sb.auth.signUp({email,password:values.password,options:{emailRedirectTo:redirectTo,data:{account_type:'profissional',full_name:values.full_name.trim(),crp:values.crp.trim(),phone:values.phone.trim(),city:values.city.trim(),specialties:values.specialties.trim(),presentation:values.presentation.trim(),privacy_accepted:true}}});button.disabled=false;if(error)return feedback('#professional-register-feedback',error.message);if(data.session){await window.sb.auth.signOut({scope:'local'});return feedback('#professional-register-feedback','É necessária a confirmação do e-mail antes do acesso.')}showConfirmation(email,redirectTo)}catch{feedback('#professional-register-feedback','Não foi possível enviar. Verifique sua conexão e tente novamente.')}finally{button.disabled=false}});

function showConfirmation(email,redirectTo){
  registerForm.innerHTML=`<div class="confirmation-state"><div class="confirmation-icon">✉</div><p>PRIMEIRA ETAPA</p><h2>Confirme seu e-mail</h2><span>O cadastro ainda <b>não está ativo</b>. Abra a mensagem enviada para <strong></strong> e clique no botão de confirmação.</span><div class="confirmation-flow"><i>1</i><b>Confirme o endereço de e-mail</b><i>2</i><b>Acompanhe o cadastro em análise</b><i>3</i><b>Aguarde a validação profissional e do CRP</b></div><button type="button" class="professional-button" id="resend-confirmation">Reenviar e-mail de ativação <span>→</span></button><button type="button" class="confirmation-login" data-view="login">Voltar para o acesso</button><div class="feedback" id="resend-feedback" role="status"></div></div>`;
  registerForm.querySelector('.confirmation-state strong').textContent=email;
  registerForm.querySelector('[data-view]').addEventListener('click',()=>showView('login'));
  const resend=registerForm.querySelector('#resend-confirmation');
  resend.addEventListener('click',async()=>{resend.disabled=true;try{feedback('#resend-feedback','Solicitando um novo envio…','success');const {error}=await window.sb.auth.resend({type:'signup',email,options:{emailRedirectTo:redirectTo}});if(error){resend.disabled=false;return feedback('#resend-feedback',error.message)}feedback('#resend-feedback','Novo e-mail solicitado. Verifique também as pastas Spam e Promoções.','success');let seconds=45;resend.textContent=`Aguarde ${seconds}s para reenviar`;const timer=setInterval(()=>{seconds-=1;resend.textContent=seconds?`Aguarde ${seconds}s para reenviar`:'Reenviar e-mail de ativação →';if(!seconds){clearInterval(timer);resend.disabled=false}},1000)}catch{resend.disabled=false;feedback('#resend-feedback','Não foi possível reenviar. Tente novamente.')}});
}
const password=registerForm.elements.password,meter=document.querySelector('#professional-password-meter');password.addEventListener('input',()=>{const value=password.value,score=[value.length>=8,/[A-Z]/.test(value),/[a-z]/.test(value),/\d/.test(value),/[^A-Za-z0-9]/.test(value)].filter(Boolean).length;meter.className=`password-meter ${score<=2?'weak':score<=4?'medium':'strong'}`;meter.querySelector('span').textContent=score<=2?'Senha fraca — acrescente diferentes caracteres.':score<=4?'Senha média — falta pouco para ficar forte.':'Senha forte — todos os requisitos foram atendidos.'});
registerForm.elements.phone.addEventListener('input',event=>{const digits=event.target.value.replace(/\D/g,'').slice(0,11);event.target.value=digits.length>6?`(${digits.slice(0,2)}) ${digits.length===11?digits.slice(2,7):digits.slice(2,6)}-${digits.length===11?digits.slice(7):digits.slice(6)}`:digits.length>2?`(${digits.slice(0,2)}) ${digits.slice(2)}`:digits});
function strongPassword(value){return value.length>=8&&/[A-Z]/.test(value)&&/[a-z]/.test(value)&&/\d/.test(value)&&/[^A-Za-z0-9]/.test(value)}
window.sb.auth.getSession().then(async({data})=>{if(!data.session)return;if(!data.session.user.email_confirmed_at){await window.sb.auth.signOut({scope:'local'});return;}const {data:profile}=await window.sb.from('profiles').select('role').eq('id',data.session.user.id).maybeSingle();if(profile?.role==='admin')return location.replace('acolher-app/');const {data:application}=await window.sb.from('professional_applications').select('id').eq('user_id',data.session.user.id).maybeSingle();if(application)location.replace('acolher-app/')}).catch(()=>feedback('#professional-login-feedback','Não foi possível verificar a conta. Tente novamente.'));
