const sb=window.sb,login=document.querySelector('#login'),shell=document.querySelector('#shell'),content=document.querySelector('#content');
let view='home',profile,patients=[],requests=[],professionals=[],appointments=[],channel,detail=null,search='',statusFilter='',busy=false;
const statusNames={nova:'Nova',em_analise:'Em análise',contato_realizado:'Contato realizado',agendada:'Agendada',em_atendimento:'Em atendimento',lista_espera:'Lista de espera',encaminhada:'Encaminhada',encerrada:'Encerrada'};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>value?new Date(value).toLocaleString('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'';
const empty=text=>`<div class="empty">${text}</div>`;
const record=(title,description,badge)=>`<article class="record"><h3>${escapeHtml(title)}</h3><span class="badge">${escapeHtml(badge)}</span><p>${escapeHtml(description)}</p></article>`;
const iconPaths={home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',patients:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M20 8v6m-3-3h6',professionals:'M12 3 3 7v6c0 5 9 9 9 9s9-4 9-9V7l-9-4Zm-4 9 3 3 5-6',agenda:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2ZM7 14h2m4 0h2m-8 4h2',more:'M5 12h.01M12 12h.01M19 12h.01',triages:'M9 3H5v18h14V3h-4M9 2h6v4H9ZM7 11l2 2 3-4m-5 8h10'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${iconPaths[name]||iconPaths.home}"/></svg>`;
document.querySelectorAll('nav button').forEach(button=>{const label=button.querySelector('span').textContent;button.innerHTML=`${icon(button.dataset.view)}<span>${label}</span>`;button.setAttribute('aria-label',label)});
function statusOptions(selected){return Object.entries(statusNames).map(([key,name])=>`<option value="${key}" ${selected===key?'selected':''}>${name}</option>`).join('')}
function requestCard(r){return `<article class="record"><h3>${escapeHtml(r.profiles?.full_name||'Paciente')}</h3><span class="badge">${escapeHtml(statusNames[r.status]||r.status)}</span><p>${escapeHtml(r.reason)} · ${escapeHtml(r.city)}</p><button class="secondary" data-detail="request" data-id="${escapeHtml(r.id)}">Abrir solicitação →</button>${contactLink(r.profiles?.phone)}</article>`}
function contactLink(phone){const digits=String(phone||'').replace(/\D/g,'');return digits?`<a href="https://wa.me/${digits.startsWith('55')?digits:'55'+digits}" target="_blank" rel="noopener">Conversar no WhatsApp ↗</a>`:''}
function patientResults(){const query=search.toLocaleLowerCase('pt-BR');const filtered=requests.filter(r=>(!statusFilter||r.status===statusFilter)&&[r.profiles?.full_name,r.city,r.reason].join(' ').toLocaleLowerCase('pt-BR').includes(query));return `<h3 class="section-title">Solicitações · ${filtered.length}</h3>${filtered.map(requestCard).join('')||empty('Nenhuma solicitação encontrada.')}<h3 class="section-title">Cadastros</h3>${patients.filter(p=>[p.full_name,p.city].join(' ').toLocaleLowerCase('pt-BR').includes(query)).map(p=>`<article class="record"><h3>${escapeHtml(p.full_name)}</h3><p>${escapeHtml(p.city||'Cidade não informada')}</p><button class="secondary" data-detail="patient" data-id="${escapeHtml(p.id)}">Ver informações →</button></article>`).join('')||empty('Nenhum cadastro encontrado.')}`}
function fields(item,labels){return `<dl>${Object.entries(labels).map(([key,label])=>`<dt>${label}</dt><dd>${escapeHtml(item[key]??'Não informado')}</dd>`).join('')}</dl>`}
function detailHtml(){const back='<button class="secondary" id="back-detail">← Voltar</button>';if(detail.type==='patient'){const p=patients.find(p=>p.id===detail.id);if(!p)return back+empty('Cadastro não encontrado.');return back+`<h2 class="section-title">${escapeHtml(p.full_name)}</h2><article class="record">${fields(p,{username:'Usuário',city:'Cidade',phone:'Telefone',address:'Endereço',social:'Rede social',created_at:'Data do cadastro'})}${contactLink(p.phone)}</article>${requests.filter(r=>r.user_id===p.id).map(requestCard).join('')}`}
 if(detail.type==='request'){const r=requests.find(r=>r.id===detail.id);if(!r)return back+empty('Solicitação não encontrada.');return back+`<h2 class="section-title">${escapeHtml(r.profiles?.full_name||'Solicitação')}</h2><article class="record">${fields(r,{for_whom:'Para quem',age:'Idade',city:'Cidade',reason:'Motivo',details:'O que foi relatado',modality:'Modalidade',preferred_period:'Período',preferred_days:'Dias',interest:'Interesse',desired_start:'Início desejado'})}${contactLink(r.profiles?.phone)}</article><form id="request-form" class="record"><label>Etapa do atendimento<select name="status">${statusOptions(r.status)}</select></label><label>Anotações administrativas<textarea name="note" rows="5">${escapeHtml(r.professional_note||'')}</textarea></label><button class="primary" type="submit">Salvar alterações</button><p class="save-feedback" role="status"></p></form>`}
 const p=professionals.find(p=>p.id===detail.id);if(!p)return back+empty('Cadastro não encontrado.');return back+`<h2 class="section-title">${escapeHtml(p.full_name)}</h2><article class="record"><span class="badge">${escapeHtml(p.status)}</span>${fields(p,{crp:'CRP informado',city:'Cidade',phone:'Telefone',specialties:'Área de atuação',presentation:'Apresentação'})}${contactLink(p.phone)}<a href="https://cadastro.cfp.org.br/" target="_blank" rel="noopener">Consultar registro no CFP ↗</a><p>A consulta automática ao CRP ainda não está integrada. A aprovação exige conferir o registro no cadastro oficial.</p></article><form id="professional-form" class="record"><label class="check"><input type="checkbox" name="checked"> Confirmei o registro e a identidade no cadastro oficial</label><div class="actions"><button class="secondary" type="submit" name="decision" value="recusado">Não aprovar</button><button class="primary" type="submit" name="decision" value="aprovado">Aprovar cadastro</button></div><p class="save-feedback" role="status"></p></form>`;
}
function bindActions(){content.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.go)));content.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{openDetail(b.dataset.detail,b.dataset.id)}));content.querySelector('#back-detail')?.addEventListener('click',()=>{if(!busy)history.back()});const refreshList=()=>{content.querySelector('#patient-results').innerHTML=patientResults();content.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{openDetail(b.dataset.detail,b.dataset.id)}))};content.querySelector('#search')?.addEventListener('input',e=>{search=e.target.value;refreshList()});content.querySelector('#filter')?.addEventListener('change',e=>{statusFilter=e.target.value;refreshList()});content.querySelector('#request-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.currentTarget);await save(e.currentTarget,'intake_requests',detail.id,{status:data.get('status'),professional_note:data.get('note'),updated_at:new Date().toISOString()})});content.querySelector('#professional-form')?.addEventListener('submit',async e=>{e.preventDefault();const decision=e.submitter?.value;if(!decision)return;const form=e.currentTarget;if(decision==='aprovado'&&!form.elements.checked.checked){form.querySelector('.save-feedback').textContent='Consulte o registro oficial antes de aprovar.';return}await save(form,'professional_applications',detail.id,{status:decision,reviewed_at:new Date().toISOString(),reviewed_by:profile.id})})}
async function save(form,table,id,changes){if(busy)return;busy=true;const buttons=[...form.querySelectorAll('button')],feedback=form.querySelector('.save-feedback');buttons.forEach(b=>b.disabled=true);feedback.textContent='Salvando…';try{const {data,error}=await sb.from(table).update(changes).eq('id',id).select('id').single();if(error||!data)throw Error('save');const items=table==='intake_requests'?requests:professionals;Object.assign(items.find(x=>x.id===id),changes);feedback.textContent='Alterações salvas e disponíveis no site.'}catch{feedback.textContent='Não foi possível salvar. Confira sua conexão e tente novamente.'}finally{busy=false;buttons.forEach(b=>b.disabled=false)}}
async function load(){
 document.querySelector('#message').textContent='Atualizando…';
 const results=await Promise.all([sb.from('profiles').select('*').eq('role','usuario').order('created_at',{ascending:false}),sb.from('intake_requests').select('*,profiles(full_name,phone,city)').order('created_at',{ascending:false}),sb.from('professional_applications').select('*').order('created_at',{ascending:false}),sb.from('appointments').select('*,profiles(full_name)').order('starts_at',{ascending:true})]);
 const errors=results.filter(r=>r.error);document.querySelector('#message').textContent=errors.length?'Algumas informações não puderam ser atualizadas. Toque em ↻ para tentar novamente.':'';
 if(!results[0].error)patients=results[0].data||[];if(!results[1].error)requests=results[1].data||[];if(!results[2].error)professionals=results[2].data||[];if(!results[3].error)appointments=results[3].data||[];render();
}
function render(){
 let html='';const pending=requests.filter(r=>r.status==='nova'),pendingPro=professionals.filter(p=>p.status==='pendente');
 if(view==='home')html=`<section class="hero-card"><span>SEU PAINEL DE CUIDADO</span><h2>${pending.length?`${pending.length} solicitações aguardam sua atenção`:'Tudo começa com uma boa escuta.'}</h2><p>Acompanhe as solicitações recebidas pelo site.</p><button data-go="patients">Ver pacientes →</button></section><div class="stats">${[[patients.length,'Pacientes','patients'],[pending.length,'Novas solicitações','triages'],[pendingPro.length,'Profissionais pendentes','professionals'],[appointments.filter(a=>a.starts_at.slice(0,10)===new Date().toLocaleDateString('en-CA')).length,'Agenda de hoje','agenda']].map(([n,t,target])=>`<button type="button" class="stat" data-go="${target}" aria-label="Abrir ${t}"><span>${t}</span><strong>${n}</strong><span class="stat-open">Abrir →</span></button>`).join('')}</div><h2 class="section-title">Últimos cadastros</h2>${patients.slice(0,5).map(p=>`<article class="record"><h3>${escapeHtml(p.full_name)}</h3><span class="badge">${escapeHtml(date(p.created_at))}</span><p>${escapeHtml(p.city||'Cidade não informada')}</p><button class="secondary" data-detail="patient" data-id="${escapeHtml(p.id)}">Ver informações →</button></article>`).join('')||empty('Os novos cadastros aparecerão aqui.')}`;
 if(view==='patients')html=`<h2 class="section-title">Pacientes e solicitações</h2><label>Buscar por nome, cidade ou motivo<input id="search" type="search" value="${escapeHtml(search)}"></label><label>Etapa do atendimento<select id="filter"><option value="">Todas as etapas</option>${statusOptions(statusFilter)}</select></label><div id="patient-results">${patientResults()}</div>`;
 if(view==='triages'||view==='contacts'){const list=requests.filter(r=>(view==='triages'?['nova','em_analise']:['contato_realizado','agendada','em_atendimento','lista_espera']).includes(r.status));html=`<h2 class="section-title">${view==='triages'?'Triagens':'Contatos e acompanhamento'}</h2>${list.map(requestCard).join('')||empty('Nenhum atendimento nesta etapa.')}`}
 if(view==='professionals')html=`<h2 class="section-title">Profissionais · ${professionals.length}</h2>${professionals.map(p=>`<article class="record"><h3>${escapeHtml(p.full_name)}</h3><span class="badge">${escapeHtml(p.status)}</span><p>${escapeHtml(p.crp)} · ${escapeHtml(p.city)}</p><button class="secondary" data-detail="professional" data-id="${escapeHtml(p.id)}">Analisar cadastro →</button></article>`).join('')||empty('Nenhum cadastro profissional recebido.')}`;
 if(view==='agenda')html=`<h2 class="section-title">Sua agenda</h2>${appointments.map(a=>record(a.profiles?.full_name||'Atendimento',`${date(a.starts_at)} · ${a.modality}`,a.status)).join('')||empty('Nenhum atendimento agendado.')}`;
 if(view==='more')html=`<h2 class="section-title">Seu espaço</h2><article class="record"><h3>${escapeHtml(profile.full_name)}</h3><p>Acesso administrativo do Espaço Acolher.</p><button class="secondary" data-go="triages">Triagens →</button><button class="secondary" data-go="contacts">Contatos e acompanhamento →</button><a href="../admin.html">Abrir painel completo do site</a></article><article class="record"><h3>Avisos de cadastros</h3><p>Os dados são atualizados enquanto o app está aberto. Avisos com o app fechado ainda não estão disponíveis nesta versão.</p></article><button class="primary" id="logout">Sair da conta</button>`;
 if(detail)html=detailHtml();
 content.innerHTML=`<div class="screen">${html}</div>`;
 content.querySelectorAll('.stat').forEach(card=>card.insertAdjacentHTML('afterbegin',`<span class="stat-icon">${icon(card.dataset.go)}</span>`));
 content.querySelectorAll('.screen>.record,.stats>.stat').forEach((card,index)=>{card.style.setProperty('--stagger',`${Math.min(index,5)*65}ms`);card.classList.add('card-arrive')});
 if(view==='home'&&!detail){const hero=content.querySelector('.hero-card');hero.insertAdjacentHTML('afterbegin',`<div class="hero-top"><span class="connection"><i></i> CONECTADO AO SITE</span><span class="hero-symbol">${icon('professionals')}</span></div>`);hero.insertAdjacentHTML('beforeend','<div class="hero-decoration" aria-hidden="true"><span></span><span></span><span></span></div>');}
 document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false')});
 bindActions();content.querySelector('#logout')?.addEventListener('click',async()=>{if(channel)await sb.removeChannel(channel);await sb.auth.signOut();shell.hidden=true;login.hidden=false;profile=null;patients=[];requests=[];professionals=[];appointments=[];content.replaceChildren()});
}
function openDetail(type,id){if(busy)return;detail={type,id};history.pushState({view,detail},'');render();window.scrollTo(0,0)}
function changeView(next){if(busy||next===view&&!detail)return;const order=['home','patients','professionals','agenda','more'];content.dataset.direction=order.indexOf(next)<order.indexOf(view)?'back':'forward';view=next;detail=null;history.pushState({view,detail},'');render();window.scrollTo({top:0,behavior:'instant'})}
async function enter(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data,error}=await sb.from('profiles').select('id,full_name,role').eq('id',user.id).single();if(error||data?.role!=='admin'){await sb.auth.signOut();return false}profile=data;login.hidden=true;shell.hidden=false;document.querySelector('#greeting').textContent=`Olá, ${data.full_name.split(' ')[0]}.`;await load();if(channel)await sb.removeChannel(channel);channel=sb.channel('acolher-app-admin');['profiles','intake_requests','professional_applications','appointments'].forEach(table=>channel.on('postgres_changes',{event:'*',schema:'public',table},()=>{if(!busy&&!detail)load();else document.querySelector('#message').textContent='Há atualizações disponíveis. Toque em ↻ após concluir sua análise.'}));channel.subscribe();return true}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const values=new FormData(e.currentTarget),button=e.currentTarget.querySelector('[type=submit]'),message=document.querySelector('#login-message');button.disabled=true;message.textContent='Verificando acesso…';try{const {error}=await sb.auth.signInWithPassword({email:`${values.get('username').trim().toLowerCase()}@admin.espacoacolher.app`,password:values.get('password')});if(error||!await enter())message.textContent='Confira seu usuário, senha e permissão administrativa.';else message.textContent=''}catch{message.textContent='Não foi possível conectar. Verifique sua internet.'}finally{button.disabled=false}});
document.querySelector('#eye').addEventListener('click',e=>{const input=document.querySelector('[name=password]');input.type=input.type==='password'?'text':'password';e.currentTarget.textContent=input.type==='password'?'Ver':'Ocultar';e.currentTarget.setAttribute('aria-label',input.type==='password'?'Mostrar senha':'Ocultar senha')});
history.replaceState({view:'home',detail:null},'');
addEventListener('popstate',event=>{content.dataset.direction='back';view=event.state?.view||'home';detail=event.state?.detail||null;if(profile)render()});
document.querySelector('nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(button)changeView(button.dataset.view)});document.querySelector('#refresh').addEventListener('click',()=>{if(!busy)load()});addEventListener('pageshow',()=>{if(profile&&!detail)load()});if(sb)enter().catch(()=>{document.querySelector('#login-message').textContent='Verifique sua conexão e tente entrar.'});
