const sb=window.sb,login=document.querySelector('#login'),shell=document.querySelector('#shell'),content=document.querySelector('#content');
let view='home',profile,patients=[],requests=[],professionals=[],channel,detail=null,search='',statusFilter='',busy=false,ownApplication=null;
const isAdmin=()=>profile?.role==='admin';
const statusNames={nova:'Nova',em_analise:'Em análise',contato_realizado:'Contato realizado',agendada:'Agendada',em_atendimento:'Em atendimento',lista_espera:'Lista de espera',encaminhada:'Encaminhada',encerrada:'Encerrada'};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>value?new Date(value).toLocaleString('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'';
const empty=text=>`<div class="empty">${text}</div>`;
const record=(title,description,badge)=>`<article class="record"><h3>${escapeHtml(title)}</h3><span class="badge">${escapeHtml(badge)}</span><p>${escapeHtml(description)}</p></article>`;
const iconPaths={home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',patients:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M20 8v6m-3-3h6',professionals:'M12 3 3 7v6c0 5 9 9 9 9s9-4 9-9V7l-9-4Zm-4 9 3 3 5-6',more:'M5 12h.01M12 12h.01M19 12h.01',triages:'M9 3H5v18h14V3h-4M9 2h6v4H9ZM7 11l2 2 3-4m-5 8h10'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${iconPaths[name]||iconPaths.home}"/></svg>`;
document.querySelectorAll('nav button').forEach(button=>{const label=button.querySelector('span').textContent;button.innerHTML=`${icon(button.dataset.view)}<span>${label}</span>`;button.setAttribute('aria-label',label)});
function statusOptions(selected){return Object.entries(statusNames).map(([key,name])=>`<option value="${key}" ${selected===key?'selected':''}>${name}</option>`).join('')}
function requestCard(r){return `<article class="record"><h3>${escapeHtml(r.profiles?.full_name||'Paciente')}</h3><span class="badge">${escapeHtml(statusNames[r.status]||r.status)}</span><p>${escapeHtml(r.reason)} · ${escapeHtml(r.city)}</p><button class="secondary" data-detail="request" data-id="${escapeHtml(r.id)}">Abrir solicitação →</button>${contactLink(r.profiles?.phone)}</article>`}
function contactLink(phone){const digits=String(phone||'').replace(/\D/g,'');return digits?`<a href="https://wa.me/${digits.startsWith('55')?digits:'55'+digits}" target="_blank" rel="noopener">Conversar no WhatsApp ↗</a>`:''}
function patientResults(){const query=search.toLocaleLowerCase('pt-BR');const filtered=requests.filter(r=>(!statusFilter||r.status===statusFilter)&&[r.profiles?.full_name,r.city,r.reason].join(' ').toLocaleLowerCase('pt-BR').includes(query));return `<h3 class="section-title">Solicitações · ${filtered.length}</h3>${filtered.map(requestCard).join('')||empty('Nenhuma solicitação encontrada.')}<h3 class="section-title">Cadastros</h3>${patients.filter(p=>[p.full_name,p.city].join(' ').toLocaleLowerCase('pt-BR').includes(query)).map(p=>`<article class="record"><h3>${escapeHtml(p.full_name)}</h3><span class="badge">${p.email_verified_at?'E-mail confirmado':'Aguardando confirmação do e-mail'}</span><p>${escapeHtml(p.city||'Cidade não informada')}</p><button class="secondary" data-detail="patient" data-id="${escapeHtml(p.id)}">Ver informações →</button></article>`).join('')||empty('Nenhum cadastro encontrado.')}`}
function fields(item,labels){return `<dl>${Object.entries(labels).map(([key,label])=>`<dt>${label}</dt><dd>${escapeHtml(item[key]??'Não informado')}</dd>`).join('')}</dl>`}
function detailHtml(){const back='<button class="secondary" id="back-detail">← Voltar</button>';if(detail.type==='patient'){const p=patients.find(p=>p.id===detail.id);if(!p)return back+empty('Cadastro não encontrado.');return back+`<h2 class="section-title">${escapeHtml(p.full_name)}</h2><article class="record">${fields(p,{email_verified_at:'E-mail confirmado em',username:'Usuário',city:'Cidade',phone:'Telefone',address:'Endereço',social:'Rede social',created_at:'Data do cadastro'})}${contactLink(p.phone)}</article>${requests.filter(r=>r.user_id===p.id).map(requestCard).join('')}`}
 if(detail.type==='request'){const r=requests.find(r=>r.id===detail.id);if(!r)return back+empty('Solicitação não encontrada.');return back+`<h2 class="section-title">${escapeHtml(r.profiles?.full_name||'Solicitação')}</h2><article class="record">${fields(r,{for_whom:'Para quem',age:'Idade',city:'Cidade',reason:'Motivo',details:'O que foi relatado',modality:'Modalidade',preferred_period:'Período',preferred_days:'Dias',interest:'Interesse',desired_start:'Início desejado'})}${contactLink(r.profiles?.phone)}</article><form id="request-form" class="record"><label>Etapa do atendimento<select name="status">${statusOptions(r.status)}</select></label><label>Anotações administrativas<textarea name="note" rows="5">${escapeHtml(r.professional_note||'')}</textarea></label><button class="primary" type="submit">Salvar alterações</button><p class="save-feedback" role="status"></p></form>`}
 const p=professionals.find(p=>p.id===detail.id);if(!p)return back+empty('Cadastro não encontrado.');return back+`<h2 class="section-title">${escapeHtml(p.full_name)}</h2><article class="record"><span class="badge">${escapeHtml(p.status)}</span>${fields(p,{crp:'CRP informado',city:'Cidade',phone:'Telefone',specialties:'Área de atuação',presentation:'Apresentação'})}${contactLink(p.phone)}<a href="https://cadastro.cfp.org.br/" target="_blank" rel="noopener">Consultar registro no CFP ↗</a><p>A consulta automática ao CRP ainda não está integrada. A aprovação exige conferir o registro no cadastro oficial.</p></article><form id="professional-form" class="record"><label class="check"><input type="checkbox" name="checked"> Confirmei o registro e a identidade no cadastro oficial</label><div class="actions"><button class="secondary" type="submit" name="decision" value="recusado">Não aprovar</button><button class="primary" type="submit" name="decision" value="aprovado">Aprovar cadastro</button></div><p class="save-feedback" role="status"></p></form>`;
}
function bindActions(){content.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.go)));content.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{openDetail(b.dataset.detail,b.dataset.id)}));content.querySelector('#back-detail')?.addEventListener('click',()=>{if(!busy)history.back()});const refreshList=()=>{content.querySelector('#patient-results').innerHTML=patientResults();content.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{openDetail(b.dataset.detail,b.dataset.id)}))};content.querySelector('#search')?.addEventListener('input',e=>{search=e.target.value;refreshList()});content.querySelector('#filter')?.addEventListener('change',e=>{statusFilter=e.target.value;refreshList()});content.querySelector('#request-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.currentTarget);await save(e.currentTarget,'intake_requests',detail.id,{status:data.get('status'),professional_note:data.get('note'),updated_at:new Date().toISOString()})});content.querySelector('#professional-form')?.addEventListener('submit',async e=>{e.preventDefault();const decision=e.submitter?.value;if(!decision)return;const form=e.currentTarget;if(decision==='aprovado'&&!form.elements.checked.checked){form.querySelector('.save-feedback').textContent='Consulte o registro oficial antes de aprovar.';return}await save(form,'professional_applications',detail.id,{status:decision,reviewed_at:new Date().toISOString(),reviewed_by:profile.id})})}
async function save(form,table,id,changes){if(busy||!isAdmin())return;busy=true;const buttons=[...form.querySelectorAll('button')],feedback=form.querySelector('.save-feedback');buttons.forEach(b=>b.disabled=true);feedback.textContent='Salvando…';try{const {data,error}=await sb.from(table).update(changes).eq('id',id).select('id').single();if(error||!data)throw Error('save');const items=table==='intake_requests'?requests:professionals;Object.assign(items.find(x=>x.id===id),changes);feedback.textContent='Alterações salvas e disponíveis no site.'}catch{feedback.textContent='Não foi possível salvar. Confira sua conexão e tente novamente.'}finally{busy=false;buttons.forEach(b=>b.disabled=false)}}
async function load(){
 if(!isAdmin()){const {data,error}=await sb.from('professional_applications').select('*').eq('user_id',profile.id).maybeSingle();ownApplication=error?null:data;professionals=[];patients=[];requests=[];document.querySelector('#message').textContent=error?'Não foi possível atualizar seu cadastro. Tente novamente.':'';render();return}
 document.querySelector('#message').textContent='Atualizando…';
 const results=await Promise.all([sb.from('profiles').select('*').eq('role','usuario').order('created_at',{ascending:false}),sb.from('intake_requests').select('*,profiles(full_name,phone,city)').order('created_at',{ascending:false}),sb.from('professional_applications').select('*').order('created_at',{ascending:false})]);
 const errors=results.filter(r=>r.error);document.querySelector('#message').textContent=errors.length?'Algumas informações não puderam ser atualizadas. Toque em ↻ para tentar novamente.':'';
 if(!results[0].error)patients=results[0].data||[];if(!results[1].error)requests=results[1].data||[];if(!results[2].error)professionals=results[2].data||[];const professionalIds=new Set(professionals.map(p=>p.user_id));patients=patients.filter(p=>!professionalIds.has(p.id));render();
}
function render(){
 let html='';const pending=requests.filter(r=>r.status==='nova'),pendingPro=professionals.filter(p=>p.status==='pendente');
 if(view==='home')html=`<div class="dashboard-caption"><span>Visão geral</span><time>${new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})}</time></div><section class="hero-card"><div class="hero-top"><span class="connection"><i></i> CENTRAL DE CUIDADO</span>${icon('triages')}</div><div class="attention-count"><strong>${pending.length+pendingPro.length}</strong><div><h2>${pending.length+pendingPro.length===1?'Item pede atenção':'Itens pedem atenção'}</h2><p>${pending.length+pendingPro.length?'Revise os novos movimentos da plataforma':'Sua gestão está em dia'}</p></div></div><div class="hero-actions-admin"><button data-go="triages">Analisar agora <span>↗</span></button><button data-go="more" aria-label="Abrir notificações">Avisos <span>→</span></button></div></section><div class="app-status-strip"><span><i></i> Sistema conectado</span><b>Dados atualizados em tempo real</b></div><div class="section-bar"><h2 class="section-title">Indicadores</h2><span>Toque para abrir</span></div><div class="stats">${[[patients.length,'Pacientes','patients'],[pending.length,'Solicitações','triages'],[pendingPro.length,'Profissionais','professionals'],[requests.filter(r=>['contato_realizado','em_atendimento','lista_espera'].includes(r.status)).length,'Em acompanhamento','contacts']].map(([n,t,target])=>`<button type="button" class="stat" data-go="${target}" aria-label="Abrir ${t}"><span>${t}</span><strong>${n}</strong><span class="stat-open">↗</span></button>`).join('')}</div><div class="section-bar"><h2 class="section-title">Movimentos recentes</h2><button data-go="patients">Ver todos →</button></div>${patients.slice(0,3).map(p=>`<button class="person-preview" data-detail="patient" data-id="${escapeHtml(p.id)}"><span class="person-avatar">${escapeHtml(p.full_name.trim().split(/\s+/).slice(0,2).map(s=>s[0]).join(''))}</span><div><strong>${escapeHtml(p.full_name)}</strong><span>${escapeHtml(p.city||'Cidade não informada')}</span></div><span>›</span></button>`).join('')||empty('Os novos cadastros aparecerão aqui.')}`;
 if(view==='patients')html=`<h2 class="section-title">Pacientes e solicitações</h2><label>Buscar por nome, cidade ou motivo<input id="search" type="search" value="${escapeHtml(search)}"></label><label>Etapa do atendimento<select id="filter"><option value="">Todas as etapas</option>${statusOptions(statusFilter)}</select></label><div id="patient-results">${patientResults()}</div>`;
 if(view==='triages'||view==='contacts'){const list=requests.filter(r=>(view==='triages'?['nova','em_analise']:['contato_realizado','agendada','em_atendimento','lista_espera']).includes(r.status));html=`<h2 class="section-title">${view==='triages'?'Triagens':'Contatos e acompanhamento'}</h2>${list.map(requestCard).join('')||empty('Nenhum atendimento nesta etapa.')}`}
 if(view==='professionals')html=`<h2 class="section-title">Profissionais · ${professionals.length}</h2>${professionals.map(p=>`<article class="record"><h3>${escapeHtml(p.full_name)}</h3><span class="badge">${escapeHtml(p.status)}</span><p>${escapeHtml(p.crp)} · ${escapeHtml(p.city)}</p><button class="secondary" data-detail="professional" data-id="${escapeHtml(p.id)}">Analisar cadastro →</button></article>`).join('')||empty('Nenhum cadastro profissional recebido.')}`;

 if(view==='more')html=`<h2 class="section-title">Seu espaço</h2><article class="record"><h3>${escapeHtml(profile.full_name)}</h3><p>Acesso administrativo do Espaço Acolher.</p><button class="secondary" data-go="triages">Triagens →</button><button class="secondary" data-go="contacts">Contatos e acompanhamento →</button></article><article class="record"><h3>Avisos de cadastros</h3><p>Ative neste celular para receber avisos de pacientes, profissionais e solicitações. O envio é feito pelo servidor, sem dados pessoais na notificação.</p>${window.AcolherNotifications?.html()||'<p>Atualize o aplicativo para configurar notificações.</p>'}</article><button class="primary" id="logout">Sair da conta</button>`;
 if(view==='personal'||!isAdmin())html=personalArea();
 if(detail&&isAdmin())html=detailHtml();
 if(isAdmin()&&view==='home')html=html.replace('</section>','<button data-go="personal" style="margin-top:10px">Minha área profissional <span>→</span></button></section>');
 content.innerHTML=`<div class="screen">${html}</div>`;
 content.querySelectorAll('.stat').forEach(card=>card.insertAdjacentHTML('afterbegin',`<span class="stat-icon">${icon(card.dataset.go)}</span>`));
 content.querySelectorAll('.screen>.record,.stats>.stat').forEach((card,index)=>{card.style.setProperty('--stagger',`${Math.min(index,5)*65}ms`);card.classList.add('card-arrive')});
 document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false')});
 bindActions();window.AcolherNotifications?.show();content.querySelector('#logout')?.addEventListener('click',async()=>{await window.AcolherNotifications?.logout();if(channel)await sb.removeChannel(channel);await sb.auth.signOut();shell.hidden=true;login.hidden=false;profile=null;patients=[];requests=[];professionals=[];content.replaceChildren()});
}
function openDetail(type,id){if(busy||!isAdmin())return;detail={type,id};history.pushState({view,detail},'');render();window.scrollTo(0,0)}
function changeView(next){if(!isAdmin())next='personal';if(busy||next===view&&!detail)return;const order=['home','patients','professionals','more'];content.dataset.direction=order.indexOf(next)<order.indexOf(view)?'back':'forward';view=next;detail=null;history.pushState({view,detail},'');render();window.scrollTo({top:0,behavior:'instant'})}
async function enter(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;if(!user.email_confirmed_at){await sb.auth.signOut({scope:'local'});return false}const {data,error}=await sb.from('profiles').select('id,full_name,role').eq('id',user.id).single();if(error||!data){await sb.auth.signOut();return false}profile=data;const own=await sb.from('professional_applications').select('*').eq('user_id',user.id).maybeSingle();ownApplication=own.error?null:own.data;if(!isAdmin()&&!ownApplication){profile=null;await sb.auth.signOut();return false}view=isAdmin()?'home':'personal';detail=null;document.querySelectorAll('nav button').forEach(b=>b.hidden=!isAdmin());login.hidden=true;shell.hidden=false;document.querySelector('#greeting').textContent=`Olá, ${data.full_name.split(' ')[0]}.`;await load();if(!isAdmin())return true;if(channel)await sb.removeChannel(channel);channel=sb.channel('acolher-app-admin');['profiles','intake_requests','professional_applications'].forEach(table=>channel.on('postgres_changes',{event:'*',schema:'public',table},()=>{if(!busy&&!detail)load();else document.querySelector('#message').textContent='Há atualizações disponíveis. Toque em ↻ após concluir sua análise.'}));channel.subscribe();return true}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const values=new FormData(e.currentTarget),button=e.currentTarget.querySelector('[type=submit]'),message=document.querySelector('#login-message');button.disabled=true;message.textContent='Verificando acesso…';try{const {error}=await sb.auth.signInWithPassword({email:loginEmail(values.get('username')),password:values.get('password')});if(error||!await enter())message.textContent='Confira seu usuário, senha e permissão administrativa.';else message.textContent=''}catch{message.textContent='Não foi possível conectar. Verifique sua internet.'}finally{button.disabled=false}});
document.querySelector('#eye').addEventListener('click',e=>{const input=document.querySelector('[name=password]');input.type=input.type==='password'?'text':'password';e.currentTarget.textContent=input.type==='password'?'Ver':'Ocultar';e.currentTarget.setAttribute('aria-label',input.type==='password'?'Mostrar senha':'Ocultar senha')});
function loginEmail(value){const login=String(value).trim().toLowerCase();return login.includes('@')?login:`${login}@admin.espacoacolher.app`}
function personalArea(){const p=ownApplication||profile;const status=ownApplication?.status;const label=status==='aprovado'?'Cadastro aprovado':status==='recusado'?'Cadastro não aprovado':status==='pendente'?'Cadastro em análise':'Administrador e profissional';return `<div class="dashboard-caption"><span>Minha área profissional</span><span>Espaço Acolher</span></div><section class="hero-card"><div class="hero-top"><span class="connection">ACESSO PESSOAL E RESERVADO</span>${icon('professionals')}</div><h2>${escapeHtml(p.full_name)}</h2><p>${escapeHtml(label)}</p>${isAdmin()?'<button data-go="home">Voltar ao painel executivo →</button>':''}</section><article class="record"><h3>Meu cadastro</h3>${fields(p,{full_name:'Nome',crp:'CRP',city:'Cidade',specialties:'Atuação'})}</article><article class="record"><h3>Pacientes e solicitações vinculados</h3><p>O vínculo de pacientes com profissionais ainda não está configurado. Nenhum cadastro de outro profissional é exibido nesta área.</p></article><button class="primary" id="logout">Sair da conta</button>`}
history.replaceState({view:'home',detail:null},'');
addEventListener('popstate',event=>{content.dataset.direction='back';view=event.state?.view||'home';detail=isAdmin()?(event.state?.detail||null):null;if(profile){if(!isAdmin())view='personal';render()}});
document.querySelector('nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(button)changeView(button.dataset.view)});document.querySelector('#refresh').addEventListener('click',()=>{if(!busy)load()});addEventListener('pageshow',()=>{if(profile&&!detail)load()});if(sb)enter().catch(()=>{document.querySelector('#login-message').textContent='Verifique sua conexão e tente entrar.'});
